name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          pr-comment: "This repo does not accept pull requests. If you'd like to make a contribution to this project, please submit PRs to the other repos in [this organization](https://github.com/BananaLang)."
